apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: jenkins
  name: jenkins-pv
  type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/jenkins
  storageClassName: manual