apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-application
  namespace: argocd
spec:
  destination:
  name: ''
  namespace: jenkins
  server: 'https://kubernetes.default.svc'
  source:
    path: jenkins
    repoURL: 'https://github.com/tymofiismyrnov/minikube-cluster'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
