- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        owner: kube
        group: kube
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      become: yes
      become_user: kube
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Get the token for joining the worker nodes
      become_user: kube
      shell: kubeadm token create  --print-join-command
      register: join_command

    - name: Get kube join command
      debug:
        msg: "{{ join_command.stdout }}"

    - name: Copy join command to local file
      become_user: kube
      ansible.builtin.copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command"

    - name: Fetch files from remote host
      fetch:
        src: /tmp/kubernetes_join_command  
        dest: /tmp/kubernetes_join_command  
        flat: yes 

      